# Dev Configuration

# API Configuration
api:
  version: "/v1"
  basePath: "/*"
  
# Certificate Configuration
cert:
  type: "PKCS12"
  path: "certs/mayorgacert.p12"
  alias: "mule-server"

# Crypto Certificate Configuration  
crypto:
  publicKeyring: "certs/MayorgaCoffee_0x123B380C_public.gpg"
  privateKeyring: "certs/MayorgaCoffee_0x123B380C_SECRET.gpg"
  
# Document Process API Configuration
document.prc:
   basePath: "/document"
   procotol: "HTTPS"
   host: ""
   port: ""
   method: "POST"
   path: "inbound"