# Dev Configuration

# API Configuration
api:
  version: "/v1"
  basePath: "/*"
  
# AS2 Listener Configuration
as2:
  path: "/document/inbound"
  connectionTimeout: "0"
  keystorePath: "certs/mayorga-keystore.jks"
  selfName: "Mayorga"
  selfAlias: "mayorga-receiver"
  selfEmail: "test@gmail.com"
  partnerName: "Costco"
  partnerAlias: "costco-sender-public"
  partnerEmail: "test1@gmail.com"
  
# Certificate Configuration
cert:
  type: "PKCS12"
  path: "certs/mayorgacert.p12"
  alias: "mule-server"

# Crypto Certificate Configuration  
crypto:
  publicKeyring: "certs/MayorgaCoffee_0x123B380C_public.gpg"
  privateKeyring: "certs/MayorgaCoffee_0x123B380C_SECRET.gpg"
  
# Document Process API Configuration
document.prc:
   basePath: "/document"
   protocol: "HTTPS"
   host: ""
   port: ""
   path: "inbound"